"""initial

Revision ID: 567ddcab4f81
Revises:
Create Date: 2022-04-05 15:55:24.382243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
from app.models.field_types import UTCDateTime

revision = '567ddcab4f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvester_status',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_harvester_status_key'), 'harvester_status', ['key'], unique=False)

    op.create_table('explorer_block',
    sa.Column('number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('parent_number', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('parent_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('state_root', sa.BINARY(length=32), nullable=False),
    sa.Column('extrinsics_root', sa.BINARY(length=32), nullable=False),
    sa.Column('datetime', UTCDateTime(timezone=True), nullable=True),
    sa.Column('author_authority_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('author_slot_number', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('author_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('count_extrinsics', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('count_events', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('count_logs', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('total_fee', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_fee_treasury', mysql.NUMERIC(precision=65, scale=0), nullable=True),
    sa.Column('total_fee_block_author', mysql.NUMERIC(precision=65, scale=0), nullable=True),
    sa.Column('total_tip', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight_normal', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight_operational', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight_mandatory', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('complete', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_explorer_block_author_account_id'), 'explorer_block', ['author_account_id'], unique=False)
    op.create_index(op.f('ix_explorer_block_complete'), 'explorer_block', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_block_hash'), 'explorer_block', ['hash'], unique=False)
    op.create_index(op.f('ix_explorer_block_number'), 'explorer_block', ['number'], unique=False)
    op.create_index(op.f('ix_explorer_block_parent_hash'), 'explorer_block', ['parent_hash'], unique=False)
    op.create_table('explorer_event',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('event_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('extrinsic_idx', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('event', sa.BINARY(length=2), nullable=True),
    sa.Column('event_module', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('phase_idx', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('phase_name', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('block_datetime', UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=True),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'event_idx')
    )
    op.create_index(op.f('ix_explorer_event_block_hash'), 'explorer_event', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_event_block_number'), 'explorer_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_event_complete'), 'explorer_event', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_event_event_idx'), 'explorer_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_explorer_event_event_module'), 'explorer_event', ['event_module'], unique=False)
    op.create_index(op.f('ix_explorer_event_event_name'), 'explorer_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_explorer_event_extrinsic_idx'), 'explorer_event', ['extrinsic_idx'], unique=False)
    op.create_table('explorer_extrinsic',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('extrinsic_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('hash', sa.BINARY(length=32), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('version_info', sa.BINARY(length=1), nullable=True),
    sa.Column('call', sa.BINARY(length=2), nullable=True),
    sa.Column('call_module', sa.String(length=255), nullable=True),
    sa.Column('call_name', sa.String(length=255), nullable=True),
    sa.Column('call_arguments', sa.JSON(), nullable=True),
    sa.Column('call_hash', sa.BINARY(length=32), nullable=True),
    sa.Column('signed', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('signature', sa.VARBINARY(length=65), nullable=True),
    sa.Column('signature_version', sa.String(length=16), nullable=True),
    sa.Column('multi_address_type', sa.String(length=16), nullable=True),
    sa.Column('multi_address_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('multi_address_account_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('multi_address_raw', sa.VARBINARY(length=255), nullable=True),
    sa.Column('multi_address_address_32', sa.BINARY(length=32), nullable=True),
    sa.Column('multi_address_address_20', sa.BINARY(length=20), nullable=True),
    sa.Column('extrinsic_length', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('nonce', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('era', sa.JSON(), nullable=True),
    sa.Column('era_immortal', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('era_birth', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('era_death', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('tip', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('block_datetime', UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=True),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_explorer_extrinsic_block_hash'), 'explorer_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_block_number'), 'explorer_extrinsic', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_call_module'), 'explorer_extrinsic', ['call_module'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_call_name'), 'explorer_extrinsic', ['call_name'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_complete'), 'explorer_extrinsic', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_extrinsic_idx'), 'explorer_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_hash'), 'explorer_extrinsic', ['hash'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_multi_address_account_id'), 'explorer_extrinsic', ['multi_address_account_id'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_signed'), 'explorer_extrinsic', ['signed'], unique=False)
    op.create_table('explorer_log',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('log_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('block_datetime', UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=True),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'log_idx')
    )
    op.create_index(op.f('ix_explorer_log_block_hash'), 'explorer_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_log_block_number'), 'explorer_log', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_log_complete'), 'explorer_log', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_log_log_idx'), 'explorer_log', ['log_idx'], unique=False)
    op.create_index(op.f('ix_explorer_log_type_id'), 'explorer_log', ['type_id'], unique=False)
    op.create_index(op.f('ix_explorer_log_type_name'), 'explorer_log', ['type_name'], unique=False)
    op.create_table('explorer_transfer',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('event_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('extrinsic_idx', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('from_multi_address_type', sa.String(length=16), nullable=True),
    sa.Column('from_multi_address_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('from_multi_address_account_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('from_multi_address_raw', sa.VARBINARY(length=255), nullable=True),
    sa.Column('from_multi_address_address_32', sa.BINARY(length=32), nullable=True),
    sa.Column('from_multi_address_address_20', sa.BINARY(length=20), nullable=True),
    sa.Column('to_multi_address_type', sa.String(length=16), nullable=True),
    sa.Column('to_multi_address_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('to_multi_address_account_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('to_multi_address_raw', sa.VARBINARY(length=255), nullable=True),
    sa.Column('to_multi_address_address_32', sa.BINARY(length=32), nullable=True),
    sa.Column('to_multi_address_address_20', sa.BINARY(length=20), nullable=True),
    sa.Column('value', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('block_datetime', UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'event_idx')
    )
    op.create_index(op.f('ix_explorer_transfer_block_hash'), 'explorer_transfer', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_block_number'), 'explorer_transfer', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_complete'), 'explorer_transfer', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_event_idx'), 'explorer_transfer', ['event_idx'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_extrinsic_idx'), 'explorer_transfer', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_from_multi_address_account_id'), 'explorer_transfer', ['from_multi_address_account_id'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_to_multi_address_account_id'), 'explorer_transfer', ['to_multi_address_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explorer_transfer_to_multi_address_account_id'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_from_multi_address_account_id'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_extrinsic_idx'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_event_idx'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_complete'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_block_number'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_block_hash'), table_name='explorer_transfer')
    op.drop_table('explorer_transfer')
    op.drop_index(op.f('ix_explorer_log_type_name'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_type_id'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_log_idx'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_complete'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_block_number'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_block_hash'), table_name='explorer_log')
    op.drop_table('explorer_log')
    op.drop_index(op.f('ix_explorer_extrinsic_signed'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_multi_address_account_id'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_hash'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_extrinsic_idx'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_complete'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_call_name'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_call_module'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_block_number'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_block_hash'), table_name='explorer_extrinsic')
    op.drop_table('explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_event_extrinsic_idx'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_event_name'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_event_module'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_event_idx'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_complete'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_block_number'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_block_hash'), table_name='explorer_event')
    op.drop_table('explorer_event')
    op.drop_index(op.f('ix_explorer_block_parent_hash'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_number'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_hash'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_complete'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_author_account_id'), table_name='explorer_block')
    op.drop_table('explorer_block')

    # ### end Alembic commands ###
