"""initial

Revision ID: 567ddcab4f81
Revises: 
Create Date: 2022-04-05 15:55:24.382243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '567ddcab4f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvester_status',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_harvester_status_key'), 'harvester_status', ['key'], unique=False)

    op.create_table('codec_block_event',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('event_module', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'event_idx')
    )
    op.create_index(op.f('ix_codec_block_event_block_hash'), 'codec_block_event', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_event_block_number'), 'codec_block_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_event_complete'), 'codec_block_event', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_event_event_idx'), 'codec_block_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_codec_block_event_event_module'), 'codec_block_event', ['event_module'], unique=False)
    op.create_index(op.f('ix_codec_block_event_event_name'), 'codec_block_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_codec_block_event_extrinsic_idx'), 'codec_block_event', ['extrinsic_idx'], unique=False)
    op.create_table('codec_block_extrinsic',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('call_module', sa.String(length=255), nullable=True),
    sa.Column('call_name', sa.String(length=255), nullable=True),
    sa.Column('signed', sa.SmallInteger(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_codec_block_extrinsic_block_hash'), 'codec_block_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_block_number'), 'codec_block_extrinsic', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_call_module'), 'codec_block_extrinsic', ['call_module'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_call_name'), 'codec_block_extrinsic', ['call_name'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_complete'), 'codec_block_extrinsic', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_extrinsic_idx'), 'codec_block_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_signed'), 'codec_block_extrinsic', ['signed'], unique=False)
    op.create_table('codec_block_header_digest_log',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('log_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'log_idx')
    )
    op.create_index(op.f('ix_codec_block_header_digest_log_block_hash'), 'codec_block_header_digest_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_block_number'), 'codec_block_header_digest_log', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_complete'), 'codec_block_header_digest_log', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_log_idx'), 'codec_block_header_digest_log', ['log_idx'], unique=False)
    op.create_table('codec_block_storage',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('storage_key', sa.VARBINARY(length=128), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('storage_module', sa.String(length=255), nullable=True),
    sa.Column('storage_name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'storage_key')
    )
    op.create_index(op.f('ix_codec_block_storage_block_hash'), 'codec_block_storage', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_block_number'), 'codec_block_storage', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_complete'), 'codec_block_storage', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_storage_key'), 'codec_block_storage', ['storage_key'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_storage_module'), 'codec_block_storage', ['storage_module'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_storage_name'), 'codec_block_storage', ['storage_name'], unique=False)
    op.create_table('codec_metadata',
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version')
    )
    op.create_index(op.f('ix_codec_metadata_complete'), 'codec_metadata', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_metadata_spec_name'), 'codec_metadata', ['spec_name'], unique=False)
    op.create_index(op.f('ix_codec_metadata_spec_version'), 'codec_metadata', ['spec_version'], unique=False)
    op.create_table('explorer_block',
    sa.Column('number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('parent_number', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('parent_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('state_root', sa.BINARY(length=32), nullable=False),
    sa.Column('extrinsics_root', sa.BINARY(length=32), nullable=False),
    sa.Column('datetime', app.models.field_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('author_authority_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('author_slot_number', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('author_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('count_extrinsics', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('count_events', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('count_logs', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('total_fee', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_fee_treasury', mysql.NUMERIC(precision=65, scale=0), nullable=True),
    sa.Column('total_fee_block_author', mysql.NUMERIC(precision=65, scale=0), nullable=True),
    sa.Column('total_tip', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight_normal', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight_operational', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('total_weight_mandatory', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('complete', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_explorer_block_author_account_id'), 'explorer_block', ['author_account_id'], unique=False)
    op.create_index(op.f('ix_explorer_block_complete'), 'explorer_block', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_block_hash'), 'explorer_block', ['hash'], unique=False)
    op.create_index(op.f('ix_explorer_block_number'), 'explorer_block', ['number'], unique=False)
    op.create_index(op.f('ix_explorer_block_parent_hash'), 'explorer_block', ['parent_hash'], unique=False)
    op.create_table('explorer_event',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('event_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('extrinsic_idx', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('event', sa.BINARY(length=2), nullable=True),
    sa.Column('event_module', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('phase_idx', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('phase_name', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('block_datetime', app.models.field_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=True),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'event_idx')
    )
    op.create_index(op.f('ix_explorer_event_block_hash'), 'explorer_event', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_event_block_number'), 'explorer_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_event_complete'), 'explorer_event', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_event_event_idx'), 'explorer_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_explorer_event_event_module'), 'explorer_event', ['event_module'], unique=False)
    op.create_index(op.f('ix_explorer_event_event_name'), 'explorer_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_explorer_event_extrinsic_idx'), 'explorer_event', ['extrinsic_idx'], unique=False)
    op.create_table('explorer_extrinsic',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('extrinsic_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('hash', sa.BINARY(length=32), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('version_info', sa.BINARY(length=1), nullable=True),
    sa.Column('call', sa.BINARY(length=2), nullable=True),
    sa.Column('call_module', sa.String(length=255), nullable=True),
    sa.Column('call_name', sa.String(length=255), nullable=True),
    sa.Column('call_arguments', sa.JSON(), nullable=True),
    sa.Column('call_hash', sa.BINARY(length=32), nullable=True),
    sa.Column('signed', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('signature', sa.VARBINARY(length=65), nullable=True),
    sa.Column('signature_version', sa.String(length=16), nullable=True),
    sa.Column('multi_address_type', sa.String(length=16), nullable=True),
    sa.Column('multi_address_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('multi_address_account_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('multi_address_raw', sa.VARBINARY(length=255), nullable=True),
    sa.Column('multi_address_address_32', sa.BINARY(length=32), nullable=True),
    sa.Column('multi_address_address_20', sa.BINARY(length=20), nullable=True),
    sa.Column('extrinsic_length', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('nonce', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('era', sa.JSON(), nullable=True),
    sa.Column('era_immortal', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('era_birth', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('era_death', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('tip', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('block_datetime', app.models.field_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=True),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_explorer_extrinsic_block_hash'), 'explorer_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_block_number'), 'explorer_extrinsic', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_call_module'), 'explorer_extrinsic', ['call_module'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_call_name'), 'explorer_extrinsic', ['call_name'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_complete'), 'explorer_extrinsic', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_extrinsic_idx'), 'explorer_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_hash'), 'explorer_extrinsic', ['hash'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_multi_address_account_id'), 'explorer_extrinsic', ['multi_address_account_id'], unique=False)
    op.create_index(op.f('ix_explorer_extrinsic_signed'), 'explorer_extrinsic', ['signed'], unique=False)
    op.create_table('explorer_log',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('log_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('block_datetime', app.models.field_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=True),
    sa.Column('spec_version', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'log_idx')
    )
    op.create_index(op.f('ix_explorer_log_block_hash'), 'explorer_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_log_block_number'), 'explorer_log', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_log_complete'), 'explorer_log', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_log_log_idx'), 'explorer_log', ['log_idx'], unique=False)
    op.create_index(op.f('ix_explorer_log_type_id'), 'explorer_log', ['type_id'], unique=False)
    op.create_index(op.f('ix_explorer_log_type_name'), 'explorer_log', ['type_name'], unique=False)
    op.create_table('explorer_transfer',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('event_idx', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('extrinsic_idx', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('from_multi_address_type', sa.String(length=16), nullable=True),
    sa.Column('from_multi_address_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('from_multi_address_account_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('from_multi_address_raw', sa.VARBINARY(length=255), nullable=True),
    sa.Column('from_multi_address_address_32', sa.BINARY(length=32), nullable=True),
    sa.Column('from_multi_address_address_20', sa.BINARY(length=20), nullable=True),
    sa.Column('to_multi_address_type', sa.String(length=16), nullable=True),
    sa.Column('to_multi_address_account_id', sa.BINARY(length=32), nullable=True),
    sa.Column('to_multi_address_account_index', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('to_multi_address_raw', sa.VARBINARY(length=255), nullable=True),
    sa.Column('to_multi_address_address_32', sa.BINARY(length=32), nullable=True),
    sa.Column('to_multi_address_address_20', sa.BINARY(length=20), nullable=True),
    sa.Column('value', mysql.NUMERIC(unsigned=True, precision=65, scale=0), nullable=True),
    sa.Column('block_datetime', app.models.field_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_number', 'event_idx')
    )
    op.create_index(op.f('ix_explorer_transfer_block_hash'), 'explorer_transfer', ['block_hash'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_block_number'), 'explorer_transfer', ['block_number'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_complete'), 'explorer_transfer', ['complete'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_event_idx'), 'explorer_transfer', ['event_idx'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_extrinsic_idx'), 'explorer_transfer', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_from_multi_address_account_id'), 'explorer_transfer', ['from_multi_address_account_id'], unique=False)
    op.create_index(op.f('ix_explorer_transfer_to_multi_address_account_id'), 'explorer_transfer', ['to_multi_address_account_id'], unique=False)
    op.create_table('runtime',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('impl_name', sa.String(length=255), nullable=True),
    sa.Column('impl_version', sa.Integer(), nullable=True),
    sa.Column('authoring_version', sa.Integer(), nullable=True),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_pallets', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version')
    )
    op.create_index(op.f('ix_runtime_spec_name'), 'runtime', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_spec_version'), 'runtime', ['spec_version'], unique=False)
    op.create_table('runtime_call',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('call_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_call_idx', sa.Integer(), nullable=False),
    sa.Column('lookup', sa.BINARY(length=2), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_arguments', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'call_name')
    )
    op.create_index(op.f('ix_runtime_call_call_name'), 'runtime_call', ['call_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_lookup'), 'runtime_call', ['lookup'], unique=False)
    op.create_index(op.f('ix_runtime_call_pallet'), 'runtime_call', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_call_spec_name'), 'runtime_call', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_spec_version'), 'runtime_call', ['spec_version'], unique=False)
    op.create_table('runtime_call_argument',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('call_name', sa.String(length=255), nullable=False),
    sa.Column('call_argument_idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'call_name', 'call_argument_idx')
    )
    op.create_index(op.f('ix_runtime_call_argument_call_argument_idx'), 'runtime_call_argument', ['call_argument_idx'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_call_name'), 'runtime_call_argument', ['call_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_name'), 'runtime_call_argument', ['name'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_pallet'), 'runtime_call_argument', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_spec_name'), 'runtime_call_argument', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_spec_version'), 'runtime_call_argument', ['spec_version'], unique=False)
    op.create_table('runtime_constant',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('constant_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_constant_idx', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'constant_name')
    )
    op.create_index(op.f('ix_runtime_constant_constant_name'), 'runtime_constant', ['constant_name'], unique=False)
    op.create_index(op.f('ix_runtime_constant_pallet'), 'runtime_constant', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_constant_pallet_constant_idx'), 'runtime_constant', ['pallet_constant_idx'], unique=False)
    op.create_index(op.f('ix_runtime_constant_spec_name'), 'runtime_constant', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_constant_spec_version'), 'runtime_constant', ['spec_version'], unique=False)
    op.create_table('runtime_error',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('error_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_idx', sa.Integer(), nullable=False),
    sa.Column('error_idx', sa.Integer(), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'error_name')
    )
    op.create_index(op.f('ix_runtime_error_error_idx'), 'runtime_error', ['error_idx'], unique=False)
    op.create_index(op.f('ix_runtime_error_error_name'), 'runtime_error', ['error_name'], unique=False)
    op.create_index(op.f('ix_runtime_error_pallet'), 'runtime_error', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_error_pallet_idx'), 'runtime_error', ['pallet_idx'], unique=False)
    op.create_index(op.f('ix_runtime_error_spec_name'), 'runtime_error', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_error_spec_version'), 'runtime_error', ['spec_version'], unique=False)
    op.create_table('runtime_event',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_event_idx', sa.Integer(), nullable=False),
    sa.Column('lookup', sa.BINARY(length=2), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_attributes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'event_name')
    )
    op.create_index(op.f('ix_runtime_event_event_name'), 'runtime_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_lookup'), 'runtime_event', ['lookup'], unique=False)
    op.create_index(op.f('ix_runtime_event_pallet'), 'runtime_event', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_event_spec_name'), 'runtime_event', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_spec_version'), 'runtime_event', ['spec_version'], unique=False)
    op.create_table('runtime_event_attribute',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_attribute_idx', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'event_name', 'event_attribute_idx')
    )
    op.create_index(op.f('ix_runtime_event_attribute_event_attribute_idx'), 'runtime_event_attribute', ['event_attribute_idx'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_event_name'), 'runtime_event_attribute', ['event_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_pallet'), 'runtime_event_attribute', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_name'), 'runtime_event_attribute', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_version'), 'runtime_event_attribute', ['spec_version'], unique=False)
    op.create_table('runtime_pallet',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet')
    )
    op.create_index(op.f('ix_runtime_pallet_pallet'), 'runtime_pallet', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_pallet_spec_name'), 'runtime_pallet', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_pallet_spec_version'), 'runtime_pallet', ['spec_version'], unique=False)
    op.create_table('runtime_storage',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('storage_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_storage_idx', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.String(length=64), nullable=True),
    sa.Column('key_prefix_pallet', sa.BINARY(length=16), nullable=True),
    sa.Column('key_prefix_name', sa.BINARY(length=16), nullable=True),
    sa.Column('key1_scale_type', sa.String(length=255), nullable=True),
    sa.Column('key1_hasher', sa.String(length=255), nullable=True),
    sa.Column('key2_scale_type', sa.String(length=255), nullable=True),
    sa.Column('key2_hasher', sa.String(length=255), nullable=True),
    sa.Column('value_scale_type', sa.String(length=255), nullable=True),
    sa.Column('is_linked', sa.Boolean(), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'storage_name')
    )
    op.create_index(op.f('ix_runtime_storage_pallet'), 'runtime_storage', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_storage_spec_name'), 'runtime_storage', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_storage_spec_version'), 'runtime_storage', ['spec_version'], unique=False)
    op.create_index(op.f('ix_runtime_storage_storage_name'), 'runtime_storage', ['storage_name'], unique=False)
    op.create_table('runtime_type',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=False),
    sa.Column('decoder_class', sa.String(length=255), nullable=True),
    sa.Column('is_core_primitive', sa.Boolean(), nullable=True),
    sa.Column('is_runtime_primitive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'scale_type')
    )
    op.create_index(op.f('ix_runtime_type_scale_type'), 'runtime_type', ['scale_type'], unique=False)
    op.create_index(op.f('ix_runtime_type_spec_name'), 'runtime_type', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_type_spec_version'), 'runtime_type', ['spec_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_type_spec_version'), table_name='runtime_type')
    op.drop_index(op.f('ix_runtime_type_spec_name'), table_name='runtime_type')
    op.drop_index(op.f('ix_runtime_type_scale_type'), table_name='runtime_type')
    op.drop_table('runtime_type')
    op.drop_index(op.f('ix_runtime_storage_storage_name'), table_name='runtime_storage')
    op.drop_index(op.f('ix_runtime_storage_spec_version'), table_name='runtime_storage')
    op.drop_index(op.f('ix_runtime_storage_spec_name'), table_name='runtime_storage')
    op.drop_index(op.f('ix_runtime_storage_pallet'), table_name='runtime_storage')
    op.drop_table('runtime_storage')
    op.drop_index(op.f('ix_runtime_pallet_spec_version'), table_name='runtime_pallet')
    op.drop_index(op.f('ix_runtime_pallet_spec_name'), table_name='runtime_pallet')
    op.drop_index(op.f('ix_runtime_pallet_pallet'), table_name='runtime_pallet')
    op.drop_table('runtime_pallet')
    op.drop_index(op.f('ix_runtime_event_attribute_spec_version'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_spec_name'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_pallet'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_event_name'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_event_attribute_idx'), table_name='runtime_event_attribute')
    op.drop_table('runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_spec_version'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_spec_name'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_pallet'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_lookup'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_event_name'), table_name='runtime_event')
    op.drop_table('runtime_event')
    op.drop_index(op.f('ix_runtime_error_spec_version'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_spec_name'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_pallet_idx'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_pallet'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_error_name'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_error_idx'), table_name='runtime_error')
    op.drop_table('runtime_error')
    op.drop_index(op.f('ix_runtime_constant_spec_version'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_spec_name'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_pallet_constant_idx'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_pallet'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_constant_name'), table_name='runtime_constant')
    op.drop_table('runtime_constant')
    op.drop_index(op.f('ix_runtime_call_argument_spec_version'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_spec_name'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_pallet'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_name'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_call_name'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_call_argument_idx'), table_name='runtime_call_argument')
    op.drop_table('runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_spec_version'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_spec_name'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_pallet'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_lookup'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_call_name'), table_name='runtime_call')
    op.drop_table('runtime_call')
    op.drop_index(op.f('ix_runtime_spec_version'), table_name='runtime')
    op.drop_index(op.f('ix_runtime_spec_name'), table_name='runtime')
    op.drop_table('runtime')
    op.drop_index(op.f('ix_explorer_transfer_to_multi_address_account_id'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_from_multi_address_account_id'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_extrinsic_idx'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_event_idx'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_complete'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_block_number'), table_name='explorer_transfer')
    op.drop_index(op.f('ix_explorer_transfer_block_hash'), table_name='explorer_transfer')
    op.drop_table('explorer_transfer')
    op.drop_index(op.f('ix_explorer_log_type_name'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_type_id'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_log_idx'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_complete'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_block_number'), table_name='explorer_log')
    op.drop_index(op.f('ix_explorer_log_block_hash'), table_name='explorer_log')
    op.drop_table('explorer_log')
    op.drop_index(op.f('ix_explorer_extrinsic_signed'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_multi_address_account_id'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_hash'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_extrinsic_idx'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_complete'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_call_name'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_call_module'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_block_number'), table_name='explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_extrinsic_block_hash'), table_name='explorer_extrinsic')
    op.drop_table('explorer_extrinsic')
    op.drop_index(op.f('ix_explorer_event_extrinsic_idx'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_event_name'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_event_module'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_event_idx'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_complete'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_block_number'), table_name='explorer_event')
    op.drop_index(op.f('ix_explorer_event_block_hash'), table_name='explorer_event')
    op.drop_table('explorer_event')
    op.drop_index(op.f('ix_explorer_block_parent_hash'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_number'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_hash'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_complete'), table_name='explorer_block')
    op.drop_index(op.f('ix_explorer_block_author_account_id'), table_name='explorer_block')
    op.drop_table('explorer_block')
    op.drop_index(op.f('ix_codec_metadata_spec_version'), table_name='codec_metadata')
    op.drop_index(op.f('ix_codec_metadata_spec_name'), table_name='codec_metadata')
    op.drop_index(op.f('ix_codec_metadata_complete'), table_name='codec_metadata')
    op.drop_table('codec_metadata')
    op.drop_index(op.f('ix_codec_block_storage_storage_name'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_storage_module'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_storage_key'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_complete'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_block_number'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_block_hash'), table_name='codec_block_storage')
    op.drop_table('codec_block_storage')
    op.drop_index(op.f('ix_codec_block_header_digest_log_log_idx'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_complete'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_block_number'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_block_hash'), table_name='codec_block_header_digest_log')
    op.drop_table('codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_extrinsic_signed'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_extrinsic_idx'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_complete'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_call_name'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_call_module'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_block_number'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_block_hash'), table_name='codec_block_extrinsic')
    op.drop_table('codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_event_extrinsic_idx'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_event_name'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_event_module'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_event_idx'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_complete'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_block_number'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_block_hash'), table_name='codec_block_event')
    op.drop_table('codec_block_event')
    # ### end Alembic commands ###
