"""Tagged Account

Revision ID: 6ee1e9759190
Revises: b20ef0859147
Create Date: 2022-07-19 16:59:41.934299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ee1e9759190'
down_revision = 'b20ef0859147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explorer_tagged_account',
    sa.Column('account_id', sa.BINARY(length=32), autoincrement=False, nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('tag_type', sa.String(length=255), nullable=False),
    sa.Column('tag_sub_type', sa.String(length=255), nullable=True),
    sa.Column('risk_level', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('risk_level_verbose', sa.String(length=255), nullable=True),
    sa.Column('originator_info', sa.JSON(), nullable=True),
    sa.Column('beneficiary_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_explorer_tagged_account_account_id'), 'explorer_tagged_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_explorer_tagged_account_risk_level'), 'explorer_tagged_account', ['risk_level'], unique=False)
    op.create_index(op.f('ix_explorer_tagged_account_tag_type'), 'explorer_tagged_account', ['tag_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explorer_tagged_account_tag_type'), table_name='explorer_tagged_account')
    op.drop_index(op.f('ix_explorer_tagged_account_risk_level'), table_name='explorer_tagged_account')
    op.drop_index(op.f('ix_explorer_tagged_account_account_id'), table_name='explorer_tagged_account')
    op.drop_table('explorer_tagged_account')
    # ### end Alembic commands ###
